"""initial schema v0.2 — all 14 tables

Revision ID: 54c4159dbf59
Revises: 
Create Date: 2026-04-24 17:53:40.937882
"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

revision = '54c4159dbf59'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('counties',
    sa.Column('county_fips', sa.String(length=5), nullable=False),
    sa.Column('dor_county_no', sa.Integer(), nullable=False),
    sa.Column('county_name', sa.String(length=100), nullable=False),
    sa.Column('state_abbr', sa.String(length=2), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('poc_county', sa.Boolean(), nullable=False),
    sa.Column('nal_last_ingested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sdf_last_ingested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cama_last_ingested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('nal_file_path', sa.String(length=500), nullable=True),
    sa.Column('sdf_file_path', sa.String(length=500), nullable=True),
    sa.Column('cama_file_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('county_fips'),
    sa.UniqueConstraint('dor_county_no')
    )
    op.create_table('county_zips',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('county_fips', sa.String(length=5), nullable=False),
    sa.Column('zip_code', sa.String(length=10), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('county_fips', 'zip_code', name='uq_county_zip')
    )
    op.create_table('email_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('template_name', sa.String(length=100), nullable=False),
    sa.Column('listing_type', sa.String(length=50), nullable=True),
    sa.Column('subject', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_name')
    )
    op.create_table('filter_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_name', sa.String(length=100), nullable=False),
    sa.Column('county_fips', sa.String(length=5), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('max_list_price', sa.Integer(), nullable=False),
    sa.Column('min_list_price', sa.Integer(), nullable=False),
    sa.Column('target_beds', sa.Integer(), nullable=False),
    sa.Column('target_baths', sa.Integer(), nullable=False),
    sa.Column('min_year_built', sa.Integer(), nullable=False),
    sa.Column('primary_max_year_built', sa.Integer(), nullable=False),
    sa.Column('rehab_cost_per_sqft', sa.Float(), nullable=False),
    sa.Column('min_arv_spread', sa.Integer(), nullable=False),
    sa.Column('min_zestimate_discount_pct', sa.Float(), nullable=False),
    sa.Column('zestimate_staleness_days', sa.Integer(), nullable=False),
    sa.Column('min_comp_sales_for_arv', sa.Integer(), nullable=False),
    sa.Column('comp_radius_miles', sa.Float(), nullable=False),
    sa.Column('comp_year_built_tolerance', sa.Integer(), nullable=False),
    sa.Column('allowed_dor_use_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('allowed_construction_classes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('allowed_foundation_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('disallowed_foundation_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('allowed_construction_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('disallowed_property_types', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('listing_type_priority', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('deal_score_weights', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('allow_automated_outreach', sa.Boolean(), nullable=False),
    sa.Column('max_outreach_attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_name')
    )
    op.create_table('ingest_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('listing_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('county_fips', sa.String(length=5), nullable=False),
    sa.Column('parcel_id', sa.String(length=30), nullable=False),
    sa.Column('listing_type', sa.String(length=50), nullable=True),
    sa.Column('list_price', sa.Integer(), nullable=True),
    sa.Column('list_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('days_on_market', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('listing_url', sa.String(length=1000), nullable=True),
    sa.Column('listing_agent_name', sa.String(length=200), nullable=True),
    sa.Column('listing_agent_email', sa.String(length=200), nullable=True),
    sa.Column('listing_agent_phone', sa.String(length=30), nullable=True),
    sa.Column('mls_number', sa.String(length=50), nullable=True),
    sa.Column('price_per_sqft', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('arv_estimate', sa.Integer(), nullable=True),
    sa.Column('arv_source', sa.String(length=20), nullable=True),
    sa.Column('rehab_cost_estimate', sa.Integer(), nullable=True),
    sa.Column('arv_spread', sa.Integer(), nullable=True),
    sa.Column('zestimate_value', sa.Integer(), nullable=True),
    sa.Column('zestimate_discount_pct', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('zestimate_fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deal_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('deal_score_version', sa.String(length=20), nullable=True),
    sa.Column('deal_score_components', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('filter_profile_id', sa.Integer(), nullable=True),
    sa.Column('passed_filters', sa.Boolean(), nullable=True),
    sa.Column('filter_rejection_reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('workflow_status', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('raw_listing_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_le_county_parcel', 'listing_events', ['county_fips', 'parcel_id'], unique=False)
    op.create_index('ix_le_deal_score', 'listing_events', ['deal_score'], unique=False)
    op.create_index('ix_le_listing_type', 'listing_events', ['listing_type'], unique=False)
    op.create_index('ix_le_status', 'listing_events', ['workflow_status'], unique=False)
    op.create_table('outreach_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permit_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('county_fips', sa.String(length=5), nullable=False),
    sa.Column('parcel_id', sa.String(length=30), nullable=False),
    sa.Column('permit_number', sa.String(length=100), nullable=True),
    sa.Column('permit_type', sa.String(length=100), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('final_date', sa.Date(), nullable=True),
    sa.Column('permit_status', sa.String(length=50), nullable=True),
    sa.Column('valuation', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('contractor_name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pr_county_parcel', 'permit_records', ['county_fips', 'parcel_id'], unique=False)
    op.create_index('ix_pr_issue_date', 'permit_records', ['issue_date'], unique=False)
    op.create_index('ix_pr_permit_type', 'permit_records', ['permit_type'], unique=False)
    op.create_table('properties',
    sa.Column('county_fips', sa.String(length=5), nullable=False),
    sa.Column('parcel_id', sa.String(length=30), nullable=False),
    sa.Column('parcel_id_normalized', sa.String(length=30), nullable=False),
    sa.Column('dor_county_no', sa.Integer(), nullable=True),
    sa.Column('assessment_year', sa.Integer(), nullable=True),
    sa.Column('dor_use_code', sa.String(length=10), nullable=True),
    sa.Column('pa_use_code', sa.String(length=10), nullable=True),
    sa.Column('just_value', sa.Integer(), nullable=True),
    sa.Column('assessed_value', sa.Integer(), nullable=True),
    sa.Column('taxable_value', sa.Integer(), nullable=True),
    sa.Column('construction_class', sa.Integer(), nullable=True),
    sa.Column('effective_year_built', sa.Integer(), nullable=True),
    sa.Column('actual_year_built', sa.Integer(), nullable=True),
    sa.Column('total_living_area', sa.Integer(), nullable=True),
    sa.Column('land_square_footage', sa.Integer(), nullable=True),
    sa.Column('num_buildings', sa.Integer(), nullable=True),
    sa.Column('num_residential_units', sa.Integer(), nullable=True),
    sa.Column('owner_name', sa.String(length=200), nullable=True),
    sa.Column('owner_address_line1', sa.String(length=200), nullable=True),
    sa.Column('owner_address_line2', sa.String(length=200), nullable=True),
    sa.Column('owner_city', sa.String(length=100), nullable=True),
    sa.Column('owner_state', sa.String(length=2), nullable=True),
    sa.Column('owner_zip', sa.String(length=10), nullable=True),
    sa.Column('situs_address', sa.String(length=300), nullable=True),
    sa.Column('situs_city', sa.String(length=100), nullable=True),
    sa.Column('situs_state', sa.String(length=2), nullable=True),
    sa.Column('zip_code', sa.String(length=10), nullable=True),
    sa.Column('absentee_owner', sa.Boolean(), nullable=True),
    sa.Column('foundation_type', sa.String(length=100), nullable=True),
    sa.Column('exterior_wall', sa.String(length=100), nullable=True),
    sa.Column('roof_type', sa.String(length=100), nullable=True),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('bathrooms', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('cama_quality_code', sa.String(length=10), nullable=True),
    sa.Column('cama_condition_code', sa.String(length=10), nullable=True),
    sa.Column('cama_enriched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('mqi_qualified', sa.Boolean(), nullable=False),
    sa.Column('mqi_qualified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mqi_rejection_reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('mqi_stage', sa.String(length=10), nullable=True),
    sa.Column('seller_probability_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('seller_score_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('permit_count', sa.Integer(), nullable=True),
    sa.Column('estimated_rehab_per_sqft', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('raw_nal_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_cama_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('nal_ingested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('county_fips', 'parcel_id'),
    sa.UniqueConstraint('county_fips', 'parcel_id', name='uq_county_parcel')
    )
    op.create_index('ix_properties_act_yr_blt', 'properties', ['actual_year_built'], unique=False)
    op.create_index('ix_properties_const_class', 'properties', ['construction_class'], unique=False)
    op.create_index('ix_properties_county_fips', 'properties', ['county_fips'], unique=False)
    op.create_index('ix_properties_dor_use_code', 'properties', ['dor_use_code'], unique=False)
    op.create_index('ix_properties_mqi_qualified', 'properties', ['mqi_qualified'], unique=False)
    op.create_index(op.f('ix_properties_parcel_id_normalized'), 'properties', ['parcel_id_normalized'], unique=False)
    op.create_index('ix_properties_zip_code', 'properties', ['zip_code'], unique=False)
    op.create_table('property_value_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('county_fips', sa.String(length=5), nullable=False),
    sa.Column('parcel_id', sa.String(length=30), nullable=False),
    sa.Column('assessment_year', sa.Integer(), nullable=False),
    sa.Column('just_value', sa.Integer(), nullable=True),
    sa.Column('assessed_value', sa.Integer(), nullable=True),
    sa.Column('taxable_value', sa.Integer(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pvh_county_parcel', 'property_value_history', ['county_fips', 'parcel_id'], unique=False)
    op.create_table('public_records_signals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('county_fips', sa.String(length=5), nullable=False),
    sa.Column('parcel_id', sa.String(length=30), nullable=False),
    sa.Column('signal_type', sa.String(length=50), nullable=False),
    sa.Column('signal_date', sa.Date(), nullable=True),
    sa.Column('case_number', sa.String(length=100), nullable=True),
    sa.Column('court_or_agency', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_date', sa.Date(), nullable=True),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_prs_county_parcel', 'public_records_signals', ['county_fips', 'parcel_id'], unique=False)
    op.create_index('ix_prs_signal_type', 'public_records_signals', ['signal_type'], unique=False)
    op.create_table('sales_comps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('county_fips', sa.String(length=5), nullable=False),
    sa.Column('parcel_id', sa.String(length=30), nullable=False),
    sa.Column('sale_price', sa.Integer(), nullable=True),
    sa.Column('sale_date', sa.Date(), nullable=True),
    sa.Column('sale_qualifier', sa.String(length=10), nullable=True),
    sa.Column('dor_use_code', sa.String(length=10), nullable=True),
    sa.Column('construction_class', sa.Integer(), nullable=True),
    sa.Column('actual_year_built', sa.Integer(), nullable=True),
    sa.Column('total_living_area', sa.Integer(), nullable=True),
    sa.Column('zip_code', sa.String(length=10), nullable=True),
    sa.Column('situs_address', sa.String(length=300), nullable=True),
    sa.Column('price_per_sqft', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('arm_length_confirmed', sa.Boolean(), nullable=False),
    sa.Column('sdf_ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sc_county_zip_year', 'sales_comps', ['county_fips', 'zip_code', 'actual_year_built'], unique=False)
    op.create_index('ix_sc_dor_use_code', 'sales_comps', ['dor_use_code'], unique=False)
    op.create_index('ix_sc_sale_date', 'sales_comps', ['sale_date'], unique=False)
    op.create_table('ui_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zestimate_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('county_fips', sa.String(length=5), nullable=False),
    sa.Column('parcel_id', sa.String(length=30), nullable=False),
    sa.Column('zestimate_value', sa.Integer(), nullable=True),
    sa.Column('zestimate_last_updated', sa.String(length=30), nullable=True),
    sa.Column('fetch_url', sa.String(length=1000), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_zc_county_parcel_fetched', 'zestimate_cache', ['county_fips', 'parcel_id', 'fetched_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_zc_county_parcel_fetched', table_name='zestimate_cache')
    op.drop_table('zestimate_cache')
    op.drop_table('ui_sessions')
    op.drop_index('ix_sc_sale_date', table_name='sales_comps')
    op.drop_index('ix_sc_dor_use_code', table_name='sales_comps')
    op.drop_index('ix_sc_county_zip_year', table_name='sales_comps')
    op.drop_table('sales_comps')
    op.drop_index('ix_prs_signal_type', table_name='public_records_signals')
    op.drop_index('ix_prs_county_parcel', table_name='public_records_signals')
    op.drop_table('public_records_signals')
    op.drop_index('ix_pvh_county_parcel', table_name='property_value_history')
    op.drop_table('property_value_history')
    op.drop_index('ix_properties_zip_code', table_name='properties')
    op.drop_index(op.f('ix_properties_parcel_id_normalized'), table_name='properties')
    op.drop_index('ix_properties_mqi_qualified', table_name='properties')
    op.drop_index('ix_properties_dor_use_code', table_name='properties')
    op.drop_index('ix_properties_county_fips', table_name='properties')
    op.drop_index('ix_properties_const_class', table_name='properties')
    op.drop_index('ix_properties_act_yr_blt', table_name='properties')
    op.drop_table('properties')
    op.drop_index('ix_pr_permit_type', table_name='permit_records')
    op.drop_index('ix_pr_issue_date', table_name='permit_records')
    op.drop_index('ix_pr_county_parcel', table_name='permit_records')
    op.drop_table('permit_records')
    op.drop_table('outreach_log')
    op.drop_index('ix_le_status', table_name='listing_events')
    op.drop_index('ix_le_listing_type', table_name='listing_events')
    op.drop_index('ix_le_deal_score', table_name='listing_events')
    op.drop_index('ix_le_county_parcel', table_name='listing_events')
    op.drop_table('listing_events')
    op.drop_table('ingest_runs')
    op.drop_table('filter_profiles')
    op.drop_table('email_templates')
    op.drop_table('county_zips')
    op.drop_table('counties')
    # ### end Alembic commands ###
